name: List files
# run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - main
jobs:
  list:
    runs-on: ubuntu-latest
    outputs:
      flow_files: ${{ steps.flows.outputs.flow_files }}
    steps:
      - uses: actions/checkout@v3
      - name: List flows
        id: flows
        run: |
          ls -R flows/**/*.py > flow_list.txt
          echo "::set-output name=flow_files::$(cat file_list.txt)"


  job:
    name: Run for each flow
    # if: ${{ needs.decision.outputs.flows_changed == 'true'}}
    needs: [list]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ${{ fromJSON(needs.list.outputs.flow_files) }}
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
